### ISSUE TITLE
[Fr] Safari version 

### ISSUE THREAD

**Issue by andrewcrook** [alin23/sidehn#2]
Could we please have a Safari version ?

**Comment by alin23** [comment]
I'll give it a try.

**Comment by alin23** [comment]
Unfortunately this doesn't seem to work, Safari doesn't run the required rulesets for modifying CSP headers that allow the injection of HN into an iframe on external websites.

I've been trying everything for the last 2 hours, but there's zero info on this. Apple engineers don't respond, there's no way to debug it because the debug APIs are missing and I can't find any other Safari extension that can modify headers so I can only assume this is not possible at the moment.
